name: fgbio_callduplexconsensusreads
description: Call duplex consensus reads from grouped reads with fgbio
keywords:
  - fgbio
  - duplex
  - bam
tools:
  - fgbio:
      description: A set of tools for working with genomic and high throughput sequencing data, including UMIs
      homepage: http://fulcrumgenomics.github.io/fgbio/
      documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/
      tool_dev_url: https://github.com/fulcrumgenomics/fgbio
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information, e.g. `[ id:'sample1' ]`
  - bam:
      type: file
      description: Input BAM file
      pattern: "*.bam"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - bam:
      type: file
      description: Output BAM file
      pattern: "*.bam"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/fgbio:2.5.21--368dab1b4f308243
    linux/arm64:
      name: community.wave.seqera.io/library/fgbio:2.5.21--561e291fd356d057
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/fgbio:2.5.21--1afc8befe439164b
    linux/arm64:
      name: oras://community.wave.seqera.io/library/fgbio:2.5.21--61a21b7736fed99a
authors:
  - "@nh13"
  - "@znorgaard"
maintainers:
  - "@nh13"
  - "@znorgaard"
